# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install runtime deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code and model artifacts produced by training
ARG MODEL_VERSION=dev
ENV MODEL_VERSION=${MODEL_VERSION}

# put your code under /app/src
COPY src/ ./src

# versioned model + features generated by src/train.py (Option B you implemented)
COPY models/model_v${MODEL_VERSION}.joblib ./models/model_v${MODEL_VERSION}.joblib
COPY models/feature_list.json ./models/feature_list.json

# Make src importable
ENV PYTHONPATH=/app/src

EXPOSE 8000

# Start API
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
